# Data source
data_source: PlanetScope  # one of: PlanetScope, Sentinel-1, Fusion
dataset_mode: STANDALONE  # one of: STANDALONE, FUSION
mode: standalone # for the model, one of: standalone, early_fusion, late_fusion

# study
study_name: ps_standalone
n_trials: 50
database_url: sqlite:///reports/hyperopt.db
seed: 42
validation_split: 0.2

data:
  training_dir: /mnt/guanabana/raid/home/pasan001/asm-mapping/data/split_0/planet/training_data
  num_workers: 9
  batch_size: [8, 16, 32]

model:
  # encoder_name: "resnet34"
  in_channels: 6  # number of input channels for PlanetScope (4 bands + 2 indices)
  epochs: 50
  threshold: 0.5


optimization:
  encoder_name: ['resnet18', 'resnet34']
  weight_decay: [1.0e-10, 1.0e-3]
  learning_rate: [1.0e-5, 1.0e-1]
  alpha: [0.05, 0.75]
  gamma: [0, 5.0]

trainer:
  accelerator: "gpu"
  devices: 1