# data source
data_source: "Fusion"  # one of: PlanetScope, Sentinel-1, Fusion
dataset_mode: "FUSION"  # one of: STANDALONE, FUSION
mode: "late_fusion" # for the model, one of: standalone, early_fusion, late_fusion

# study
study_name: "lf_optuna_optimization"
n_trials: 20
database_url: "sqlite:///reports/fusion_hyperopt.db"
seed: 42
validation_split: 0.3

data:
  training_dir: "/mnt/guanabana/raid/home/pasan001/asm-mapping/data"
  num_workers: 4
  batch_size: [8, 16, 32]
  pad: False

model:
  in_channels: 6 
  epochs: 40
  threshold: 0.5

# parameters to optimize
fusion:
  type: ["CONCATENATE", "SUM", "AVERAGE"]
  resample_strategy: ["UPSAMPLE_S1", "DOWNSAMPLE_PLANET"]
  initial_weights: [0.7, 0.3]
  s1_in_channels: 3
  planet_in_channels: 6

optimization:
  encoder_name: ["resnet18", "resnet34"]
  weight_decay: [1.0e-6, 1.0e-4]
  learning_rate: [1.0e-5, 5.0e-4]
  alpha: [0.25, 0.75]
  gamma: [0, 3.0]

trainer:
  accelerator: "gpu"
  devices: [0]