# General settings
seed: 42
dataset_mode: STANDALONE # one of: STANDALONE, FUSION, INFERENCE (from DatasetMode enum)
data_source: PlanetScope # one of: PlantScope, Sentinel1, Fusion

# Model parameters
mode: standalone # one ofç standalone, early_fusion, late_fusion
encoder_name: "resnet18"
decoder_attention_type: "scse"
learning_rate: 0.00033863497582849194
weight_decay: 7.284742104977489e-9
decoder_use_batchnorm: True
in_channels: 6 # (6 for PlanetScope, 2 for Sentinel-1)
threshold: 0.5
alpha: 0.65
gamma: 5.0

# Dataset parameters
test_dir: "/mnt/guanabana/raid/home/pasan001/asm-mapping/data/split_0/planet/testing_data"
pad: False

# Test parameters
batch_size: 16
num_workers: 4
persistent_workers: true
pin_memory: true
prefetch_factor: 2

# Model loading
model_path: "/mnt/guanabana/raid/home/pasan001/asm-mapping/models/checkpoints/ps_trial31_f1_final.pth"

# Hardware settings
gpus: 1