# Data
data_source: PlanetScope  # one of: PlanetScope, Sentinel-1, Fusion
dataset_mode: STANDALONE  # one of: STANDALONE, FUSION, INFERENCE (from DatasetMode enum)
training_dir: /mnt/guanabana/raid/home/pasan001/asm-mapping/data/split_0/planet/training_data
# pad: True # Apply or not padding

# Model
mode: standalone  # one of: standalone, early_fusion, late_fusion
in_channels: 6  # number of input channels for PlanetScope (4 bands + 2 indices)
encoder_name: resnet34
decoder_attention_type: scse

# Training
train_val_split: 0.8
val_check_interval: 1.0
epochs: 100
learning_rate: 0.001
weight_decay: 0.0001
threshold: 0.5  # classification threshold
alpha: 0.25  # focal loss parameter
gamma: 2.0  # focal loss parameter

# Dataloaders options
num_workers: 4
pin_memory: True
persistent_workers: True
prefetch_factor: 2
batch_size: 16
train_loader_shuffle: True
val_loader_shuffle: False

# Callbacks
early_stopping:
  monitor: val_loss
  patience: 10
  mode: min

# Checkpoints and Logging
checkpoint_name: ps_0
checkpoint_dir: models/checkpoints/
log_dir: logs/
experiment_name: planetscope_standalone

# Hardware
gpus: 1

# Reproducibility
seed: 42

# Augmentation
augmentation:
  enabled: true
  horizontal_flip: true
  vertical_flip: true
  random_rotate: true